### ISSUE TITLE
Theme colour in festival submission interface possibly wrong

### ISSUE THREAD

**Issue by kafkham** [JeffThorslund/rapid-riot#8]
## Overview
Colour is showing as deep purple but based on the project colour scheme it looks like it should be white. 
### To Reproduce
Problem occurred with Safari 16.1 on macOS Ventura 13.0.1. When tested using Google Chrome, the window is white as expected. 
### Screenshot (Safari)
![Screenshot 2022-11-27 at 8 52 55 PM](https://user-images.githubusercontent.com/106843065/204175230-ab910005-c479-4ef3-8e97-2f4d90dca2a2.png)
### Screenshot (Chrome)
![Screenshot 2022-11-27 at 8 58 13 PM](https://user-images.githubusercontent.com/106843065/204175613-d47e583a-6f06-4b9d-b53b-572d2cbcd3e3.png)

**Comment by JeffThorslund** [comment]
Good catch! Are you able to dig into this and submit a PR?

**Comment by kafkham** [comment]
Hi Jeff - I found the issue and left you a PR.

**Comment by JeffThorslund** [comment]
Thanks! Deployed to production!
